
FROM golang:1.25.1-alpine3.22
WORKDIR /app
RUN apk add --no-cache git
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go install github.com/air-verse/air@latest
EXPOSE 8080
CMD ["air", "-c", "/app/.air.toml"]