services:
  palworld-helper:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      # Monter le code source pour hot reload
      - ./web:/root/web:ro
      - ./cmd:/app/cmd:ro
      - ./internal:/app/internal:ro
      - ./data/:/app/data
      # Configuration Air
      - ./.air.toml:/app/.air.toml:ro
    environment:
      - GO_ENV=development
    # Forcer Air à utiliser la config
    command: sh -c "cd /app && air -c .air.toml"